import MainNavbar from '@/components/MainNavbar'
import './globals.css'
import { Inter } from 'next/font/google'
// import localFont from 'next/font/local'
import ReduxProvider from '@/store/provider';

const inter = Inter({ subsets: ['latin'] })

// const Amsi = localFont({
//   src: [
//     {
//       path: '../assets/fonts/AmsiProCond-Regular.otf',
//       weight: '500'
//     }
//   ],
//   variable: '--font-amsi'
// })

export const metadata = {
  title: 'Wahoo Predict',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavbar />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
